/**
 * The SOC 2 Trust Services Criteria ↔ AWS check mapping — REPO-OWNED (DESIGN §5).
 *
 * Phase 0 (2026-09-02) found AWS Audit Manager closed to new accounts, so this
 * table is the product's own, outright: versioned content, reviewed like code,
 * and the single place a control's "why an auditor cares" prose lives. The
 * technical checks come from Security Hub's CIS 1.2.0 + FSBP 1.0.0 standards;
 * this table translates them into auditor language and groups them under the
 * criteria an auditor walks.
 *
 * Rules:
 *  - Every entry maps ONE Security Hub control id to the criteria it evidences.
 *  - A control the table doesn't know still shows in the gap report (flagged
 *    "unmapped") — the table failing behind AWS must never hide a finding.
 *  - Bump MAPPING_VERSION on any change; the sidecar's `sync` check diffs this
 *    table against the LIVE standards list so AWS renames surface as a task,
 *    not as silent drift (risk register: "mapping drift").
 */
import type { MappedCheck, StandardId, TscId } from "./types";

export const MAPPING_VERSION = "2026.09.0";

/** Auditor-facing names + plain descriptions for each criteria group. */
export const TSC_META: Record<TscId, { name: string; description: string }> = {
  CC1: { name: "Control environment", description: "How responsibility and oversight are set up." },
  CC2: { name: "Communication & information", description: "How the company informs people about controls and duties." },
  CC3: { name: "Risk assessment", description: "How risks are identified and weighed." },
  CC4: { name: "Monitoring activities", description: "How the company checks its controls keep working." },
  CC5: { name: "Control activities", description: "The day-to-day controls that carry out policy." },
  CC6: { name: "Logical & physical access", description: "Who and what can reach systems and data, and how that is limited." },
  CC7: { name: "System operations", description: "How problems and intrusions are detected and handled." },
  CC8: { name: "Change management", description: "How changes to systems are tracked, reviewed and rolled out." },
  CC9: { name: "Risk mitigation", description: "How business disruption and vendor risk are reduced." },
  A1: { name: "Availability", description: "Keeping the system up, backed up, and recoverable." },
  C1: { name: "Confidentiality", description: "Protecting information designated confidential." },
};

const cis = (
  checkId: string,
  tsc: TscId[],
  auditorNote: string,
  fix: string,
): MappedCheck => ({ checkId, standard: "cis-1.2.0" as StandardId, tsc, auditorNote, fix });

const fsbp = (
  checkId: string,
  tsc: TscId[],
  auditorNote: string,
  fix: string,
): MappedCheck => ({ checkId, standard: "fsbp-1.0.0" as StandardId, tsc, auditorNote, fix });

/**
 * The table. Ordering is by standard then control id — the gap report regroups
 * by TSC, so order here is for review diffs, not display.
 */
export const MAPPING: MappedCheck[] = [
  // ---- CIS AWS Foundations Benchmark v1.2.0 (the Security Hub subset) ----
  cis("CIS.1.1", ["CC6"],
    "The root account bypasses every access control you will show the auditor; day-to-day use of it undermines the whole access story.",
    "Create individual IAM identities for daily work and lock the root account away for the rare tasks only it can do."),
  cis("CIS.1.2", ["CC6"],
    "A console password without a second factor is a single stolen secret away from account access — auditors test MFA coverage early.",
    "Enable MFA for every IAM user that has a console password."),
  cis("CIS.1.3", ["CC6"],
    "Credentials nobody uses are standing attack surface, and they usually belong to people who left — exactly what offboarding reviews look for.",
    "Disable credentials unused for 90 days or more."),
  cis("CIS.1.4", ["CC6"],
    "Long-lived access keys accumulate exposure (scripts, laptops, repos); rotation bounds how long a leaked key works.",
    "Rotate every access key at least every 90 days."),
  cis("CIS.1.5", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one uppercase letter in the IAM password policy."),
  cis("CIS.1.6", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one lowercase letter in the IAM password policy."),
  cis("CIS.1.7", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one symbol in the IAM password policy."),
  cis("CIS.1.8", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one number in the IAM password policy."),
  cis("CIS.1.9", ["CC6"],
    "Minimum length is the strongest single password rule; 14+ is the benchmark auditors compare against.",
    "Set the IAM password policy minimum length to 14 or more."),
  cis("CIS.1.10", ["CC6"],
    "Password reuse lets one old breach unlock current systems.",
    "Enable password-reuse prevention in the IAM password policy."),
  cis("CIS.1.11", ["CC6"],
    "Expiry bounds how long a compromised password stays valid.",
    "Expire IAM passwords within 90 days in the password policy."),
  cis("CIS.1.12", ["CC6"],
    "A root access key is a programmatic super-credential with no owner review path — its existence alone is a finding.",
    "Delete any access key on the root account."),
  cis("CIS.1.13", ["CC6"],
    "Root without MFA means one password protects the entire account — the highest-impact single control there is.",
    "Enable MFA on the root account."),
  cis("CIS.1.14", ["CC6"],
    "Hardware MFA on root removes the phishable channel for the account's most powerful identity.",
    "Register a hardware MFA device for the root account."),
  cis("CIS.1.16", ["CC6"],
    "Permissions attached to individuals are invisible to group-level review; auditors ask how you review access, and per-user policies have no good answer.",
    "Attach IAM policies to groups or roles, never directly to users."),
  cis("CIS.1.20", ["CC7"],
    "Incident response needs a working escalation path to AWS itself; a support role is the evidence that path exists.",
    "Create an IAM role that permits managing incidents with AWS Support."),
  cis("CIS.1.22", ["CC6"],
    "A policy granting *:* is standing admin access; auditors treat every holder as a privileged user needing justification.",
    "Replace policies that allow full administrative privileges with least-privilege policies."),
  cis("CIS.2.1", ["CC7", "CC4"],
    "CloudTrail is the audit trail auditors sample activity from; without it in all regions, the period has holes you cannot backfill.",
    "Enable CloudTrail in all regions."),
  cis("CIS.2.2", ["CC7"],
    "Log-file validation proves the audit trail wasn't altered — it turns logs into evidence.",
    "Enable CloudTrail log file validation."),
  cis("CIS.2.3", ["CC6", "C1"],
    "A publicly readable audit-log bucket leaks the account's entire activity history.",
    "Block public access on the S3 bucket that stores CloudTrail logs."),
  cis("CIS.2.4", ["CC7"],
    "Logs that reach CloudWatch can raise alarms in minutes; logs only in S3 are reviewed after the fact, if ever.",
    "Integrate CloudTrail trails with CloudWatch Logs."),
  cis("CIS.2.5", ["CC8", "CC7"],
    "AWS Config is the change record — what changed, when, from what to what. It is the backbone of change-management evidence for the infrastructure.",
    "Enable AWS Config in all regions."),
  cis("CIS.2.6", ["CC7"],
    "Access logging on the log bucket answers 'who read the audit trail' — a question auditors ask about the logs themselves.",
    "Enable S3 access logging on the CloudTrail bucket."),
  cis("CIS.2.7", ["CC6", "C1"],
    "Encrypting the audit trail with a customer-managed key limits who can read the account's activity history.",
    "Encrypt CloudTrail logs at rest with a customer-managed KMS key."),
  cis("CIS.2.8", ["CC6"],
    "Key rotation bounds the blast radius of an exposed encryption key.",
    "Enable rotation for customer-created KMS keys."),
  cis("CIS.2.9", ["CC7"],
    "VPC flow logs are the network's audit trail — without them, investigating an incident has no network record to consult.",
    "Enable VPC flow logging in all VPCs."),
  cis("CIS.3.1", ["CC7"],
    "An alarm on unauthorized API calls is detection working in practice, not just logging in principle.",
    "Create a log metric filter and alarm for unauthorized API calls."),
  cis("CIS.3.2", ["CC7", "CC6"],
    "Sign-ins without MFA should be rare and noticed; the alarm is the noticing.",
    "Create a log metric filter and alarm for console sign-in without MFA."),
  cis("CIS.3.3", ["CC7", "CC6"],
    "Root usage should be an event, not a habit — the alarm makes every use reviewable.",
    "Create a log metric filter and alarm for root account usage."),
  cis("CIS.3.4", ["CC7", "CC6"],
    "IAM policy changes alter who can do what; alerting on them is how privilege changes get a second pair of eyes.",
    "Create a log metric filter and alarm for IAM policy changes."),
  cis("CIS.3.5", ["CC7"],
    "Turning the audit trail off is the first move in covering tracks; this alarm watches the watcher.",
    "Create a log metric filter and alarm for CloudTrail configuration changes."),
  cis("CIS.3.6", ["CC7", "CC6"],
    "Repeated authentication failures are the visible edge of a credential attack.",
    "Create a log metric filter and alarm for console authentication failures."),
  cis("CIS.3.7", ["CC7"],
    "Disabling or scheduling deletion of an encryption key can silently strand or expose data; it deserves an alert.",
    "Create a log metric filter and alarm for disabling or scheduled deletion of customer-managed keys."),
  cis("CIS.3.8", ["CC7"],
    "S3 bucket policy changes can flip data from private to public in one call.",
    "Create a log metric filter and alarm for S3 bucket policy changes."),
  cis("CIS.3.9", ["CC7", "CC8"],
    "Changes to AWS Config alter the change record itself — the evidence pipeline needs its own alarm.",
    "Create a log metric filter and alarm for AWS Config configuration changes."),
  cis("CIS.3.10", ["CC7", "CC8"],
    "Security group changes are firewall changes; the alarm gives each one a review moment.",
    "Create a log metric filter and alarm for security group changes."),
  cis("CIS.3.11", ["CC7", "CC8"],
    "NACL changes alter network exposure at the subnet level.",
    "Create a log metric filter and alarm for changes to Network Access Control Lists."),
  cis("CIS.3.12", ["CC7", "CC8"],
    "New or changed gateways change how traffic can enter and leave the network.",
    "Create a log metric filter and alarm for changes to network gateways."),
  cis("CIS.3.13", ["CC7", "CC8"],
    "Route table changes redirect traffic — quietly, if nobody is alerted.",
    "Create a log metric filter and alarm for route table changes."),
  cis("CIS.3.14", ["CC7", "CC8"],
    "VPC-level changes (peering, tenancy) reshape the network boundary.",
    "Create a log metric filter and alarm for VPC changes."),
  cis("CIS.4.1", ["CC6"],
    "SSH open to the whole internet is the classic exposure finding; auditors expect management ports to be restricted.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 22."),
  cis("CIS.4.2", ["CC6"],
    "RDP open to the whole internet invites brute force against the widest audience possible.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 3389."),
  cis("CIS.4.3", ["CC6"],
    "The default security group is attached implicitly; leaving it open means new resources start exposed by default.",
    "Restrict all traffic in every VPC's default security group."),

  // ---- AWS Foundational Security Best Practices v1.0.0 (high-value subset) ----
  fsbp("IAM.1", ["CC6"],
    "A policy granting *:* is standing admin access; auditors treat every holder as a privileged user needing justification.",
    "Replace IAM policies that allow full administrative privileges with least-privilege policies."),
  fsbp("IAM.2", ["CC6"],
    "Permissions attached to individuals are invisible to group-level review and outlive role changes.",
    "Attach permissions to groups or roles and remove policies attached directly to users."),
  fsbp("IAM.3", ["CC6"],
    "Long-lived access keys accumulate exposure; rotation bounds how long a leaked key works.",
    "Rotate every IAM access key at least every 90 days."),
  fsbp("IAM.4", ["CC6"],
    "A root access key is a programmatic super-credential with no owner review path.",
    "Delete any access key on the root account."),
  fsbp("IAM.5", ["CC6"],
    "A console password without a second factor is a single stolen secret away from account access.",
    "Enable MFA for every IAM user with a console password."),
  fsbp("IAM.6", ["CC6"],
    "Hardware MFA on root removes the phishable channel for the account's most powerful identity.",
    "Register a hardware MFA device for the root account."),
  fsbp("IAM.7", ["CC6"],
    "The password policy is baseline configuration evidence auditors sample.",
    "Strengthen the IAM password policy (length, complexity, reuse, expiry)."),
  fsbp("IAM.8", ["CC6"],
    "Credentials nobody uses usually belong to people who left — offboarding reviews look here first.",
    "Remove or disable IAM user credentials unused for 90 days."),
  fsbp("S3.1", ["CC6", "C1"],
    "Account-level Block Public Access is the seatbelt that makes a single misconfigured bucket a non-event.",
    "Turn on S3 Block Public Access at the account level."),
  fsbp("S3.2", ["CC6", "C1"],
    "A publicly readable bucket is the most common cloud data leak there is.",
    "Block public read access on every bucket."),
  fsbp("S3.3", ["CC6", "C1"],
    "Publicly writable storage lets anyone plant or replace your data.",
    "Block public write access on every bucket."),
  fsbp("S3.4", ["CC6", "C1"],
    "Encryption at rest is table-stakes evidence for data protection questions.",
    "Enable default server-side encryption on every bucket."),
  fsbp("S3.5", ["CC6", "C1"],
    "Allowing plain-HTTP requests lets data cross the network unencrypted.",
    "Add a bucket policy denying requests that don't use TLS (aws:SecureTransport)."),
  fsbp("S3.8", ["CC6", "C1"],
    "Bucket-level Block Public Access protects buckets even when the account-level guard is loosened.",
    "Turn on Block Public Access on each bucket."),
  fsbp("CloudTrail.1", ["CC7", "CC4"],
    "CloudTrail is the audit trail auditors sample activity from; a multi-region trail leaves no regional blind spots.",
    "Create a multi-region CloudTrail trail capturing management events."),
  fsbp("CloudTrail.2", ["CC6", "C1"],
    "Encrypting the audit trail limits who can read the account's activity history.",
    "Enable KMS encryption on CloudTrail logs."),
  fsbp("CloudTrail.4", ["CC7"],
    "Log-file validation proves the audit trail wasn't altered — it turns logs into evidence.",
    "Enable CloudTrail log file validation."),
  fsbp("CloudTrail.5", ["CC7"],
    "Logs that reach CloudWatch can raise alarms in minutes instead of being reviewed after the fact.",
    "Send CloudTrail logs to CloudWatch Logs."),
  fsbp("Config.1", ["CC8", "CC7"],
    "AWS Config is the change record — the backbone of change-management evidence for the infrastructure.",
    "Enable AWS Config with resource recording in this region."),
  fsbp("EC2.2", ["CC6"],
    "The default security group is attached implicitly; leaving it open means new resources start exposed by default.",
    "Restrict all traffic in every VPC's default security group."),
  fsbp("EC2.3", ["CC6", "C1"],
    "A public EBS snapshot hands a full disk image to anyone who asks.",
    "Make EBS snapshots private."),
  fsbp("EC2.6", ["CC7"],
    "VPC flow logs are the network's audit trail for incident investigation.",
    "Enable VPC flow logging in all VPCs."),
  fsbp("EC2.7", ["CC6", "C1"],
    "Default EBS encryption makes every new volume encrypted without anyone remembering to ask.",
    "Enable EBS encryption by default in this region."),
  fsbp("EC2.8", ["CC6"],
    "IMDSv2 stops the credential-stealing trick (SSRF against the metadata endpoint) that turned many web bugs into cloud breaches.",
    "Require IMDSv2 on EC2 instances."),
  fsbp("EC2.13", ["CC6"],
    "SSH open to the whole internet is the classic exposure finding.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 22."),
  fsbp("EC2.14", ["CC6"],
    "RDP open to the whole internet invites brute force against the widest audience possible.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 3389."),
  fsbp("RDS.1", ["CC6", "C1"],
    "A public RDS snapshot hands your database to anyone who asks.",
    "Make RDS snapshots private."),
  fsbp("RDS.2", ["CC6"],
    "A database reachable from the internet exposes your data store to the whole world's password guesses.",
    "Disable public accessibility on RDS instances."),
  fsbp("RDS.3", ["CC6", "C1"],
    "Encryption at rest for databases is one of the first data-protection answers auditors verify.",
    "Enable storage encryption on RDS instances."),
  fsbp("RDS.11", ["A1"],
    "Automatic backups are the recovery story for the availability criteria — no backups, no story.",
    "Enable automatic backups with a sensible retention period on RDS instances."),
  fsbp("DynamoDB.2", ["A1"],
    "Point-in-time recovery is what lets you answer 'and if the table is corrupted or deleted?'",
    "Enable point-in-time recovery on DynamoDB tables."),
  fsbp("Lambda.1", ["CC6"],
    "A function policy that allows public invocation makes your code an open endpoint.",
    "Remove public access from Lambda function resource policies."),
  fsbp("Lambda.2", ["CC7", "CC8"],
    "Runtimes past end-of-life stop receiving security patches — running one is unmanaged risk.",
    "Migrate Lambda functions to supported runtimes."),
  fsbp("KMS.4", ["CC6"],
    "Key rotation bounds the blast radius of an exposed encryption key.",
    "Enable rotation on customer-managed KMS keys."),
  fsbp("GuardDuty.1", ["CC7"],
    "GuardDuty is managed threat detection; auditors read it as the intrusion-detection control for the account.",
    "Enable GuardDuty in this region."),
  fsbp("ACM.1", ["CC6"],
    "An expired certificate breaks TLS — availability and trust fail at the same moment.",
    "Renew or remove expiring/expired ACM certificates (enable managed renewal)."),
];

const byId = new Map<string, MappedCheck>(MAPPING.map((m) => [`${m.standard}:${m.checkId}`, m]));

/** Look up the mapping for a control, by standard + Security Hub control id. */
export function findMapping(standard: StandardId, checkId: string): MappedCheck | undefined {
  return byId.get(`${standard}:${checkId}`);
}
