/**
 * The SOC 2 Trust Services Criteria ↔ AWS check mapping — REPO-OWNED (DESIGN §5).
 *
 * Phase 0 (2026-09-02) found AWS Audit Manager closed to new accounts, so this
 * table is the product's own, outright: versioned content, reviewed like code,
 * and the single place a control's "why an auditor cares" prose lives. The
 * technical checks come from Security Hub's CIS 1.2.0 + FSBP 1.0.0 standards;
 * this table translates them into auditor language and groups them under the
 * criteria an auditor walks.
 *
 * Rules:
 *  - Every entry maps ONE Security Hub control id to the criteria it evidences.
 *  - A control the table doesn't know still shows in the gap report (flagged
 *    "unmapped") — the table failing behind AWS must never hide a finding.
 *  - Bump MAPPING_VERSION on any change; the sidecar's `sync` check diffs this
 *    table against the LIVE standards list so AWS renames surface as a task,
 *    not as silent drift (risk register: "mapping drift").
 */
import type { MappedCheck, StandardId, TscId } from "./types";

export const MAPPING_VERSION = "2026.09.1";

/** Auditor-facing names + plain descriptions for each criteria group. */
export const TSC_META: Record<TscId, { name: string; description: string }> = {
  CC1: { name: "Control environment", description: "How responsibility and oversight are set up." },
  CC2: { name: "Communication & information", description: "How the company informs people about controls and duties." },
  CC3: { name: "Risk assessment", description: "How risks are identified and weighed." },
  CC4: { name: "Monitoring activities", description: "How the company checks its controls keep working." },
  CC5: { name: "Control activities", description: "The day-to-day controls that carry out policy." },
  CC6: { name: "Logical & physical access", description: "Who and what can reach systems and data, and how that is limited." },
  CC7: { name: "System operations", description: "How problems and intrusions are detected and handled." },
  CC8: { name: "Change management", description: "How changes to systems are tracked, reviewed and rolled out." },
  CC9: { name: "Risk mitigation", description: "How business disruption and vendor risk are reduced." },
  A1: { name: "Availability", description: "Keeping the system up, backed up, and recoverable." },
  C1: { name: "Confidentiality", description: "Protecting information designated confidential." },
};

const cis = (
  checkId: string,
  tsc: TscId[],
  auditorNote: string,
  fix: string,
): MappedCheck => ({ checkId, standard: "cis-1.2.0" as StandardId, tsc, auditorNote, fix });

const fsbp = (
  checkId: string,
  tsc: TscId[],
  auditorNote: string,
  fix: string,
): MappedCheck => ({ checkId, standard: "fsbp-1.0.0" as StandardId, tsc, auditorNote, fix });

/**
 * The table. Ordering is by standard then control id — the gap report regroups
 * by TSC, so order here is for review diffs, not display.
 */
export const MAPPING: MappedCheck[] = [
  // ---- CIS AWS Foundations Benchmark v1.2.0 (the Security Hub subset) ----
  cis("CIS.1.1", ["CC6"],
    "The root account bypasses every access control you will show the auditor; day-to-day use of it undermines the whole access story.",
    "Create individual IAM identities for daily work and lock the root account away for the rare tasks only it can do."),
  cis("CIS.1.2", ["CC6"],
    "A console password without a second factor is a single stolen secret away from account access — auditors test MFA coverage early.",
    "Enable MFA for every IAM user that has a console password."),
  cis("CIS.1.3", ["CC6"],
    "Credentials nobody uses are standing attack surface, and they usually belong to people who left — exactly what offboarding reviews look for.",
    "Disable credentials unused for 90 days or more."),
  cis("CIS.1.4", ["CC6"],
    "Long-lived access keys accumulate exposure (scripts, laptops, repos); rotation bounds how long a leaked key works.",
    "Rotate every access key at least every 90 days."),
  cis("CIS.1.5", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one uppercase letter in the IAM password policy."),
  cis("CIS.1.6", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one lowercase letter in the IAM password policy."),
  cis("CIS.1.7", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one symbol in the IAM password policy."),
  cis("CIS.1.8", ["CC6"],
    "Password complexity rules are among the first configuration evidence an auditor samples.",
    "Require at least one number in the IAM password policy."),
  cis("CIS.1.9", ["CC6"],
    "Minimum length is the strongest single password rule; 14+ is the benchmark auditors compare against.",
    "Set the IAM password policy minimum length to 14 or more."),
  cis("CIS.1.10", ["CC6"],
    "Password reuse lets one old breach unlock current systems.",
    "Enable password-reuse prevention in the IAM password policy."),
  cis("CIS.1.11", ["CC6"],
    "Expiry bounds how long a compromised password stays valid.",
    "Expire IAM passwords within 90 days in the password policy."),
  cis("CIS.1.12", ["CC6"],
    "A root access key is a programmatic super-credential with no owner review path — its existence alone is a finding.",
    "Delete any access key on the root account."),
  cis("CIS.1.13", ["CC6"],
    "Root without MFA means one password protects the entire account — the highest-impact single control there is.",
    "Enable MFA on the root account."),
  cis("CIS.1.14", ["CC6"],
    "Hardware MFA on root removes the phishable channel for the account's most powerful identity.",
    "Register a hardware MFA device for the root account."),
  cis("CIS.1.16", ["CC6"],
    "Permissions attached to individuals are invisible to group-level review; auditors ask how you review access, and per-user policies have no good answer.",
    "Attach IAM policies to groups or roles, never directly to users."),
  cis("CIS.1.20", ["CC7"],
    "Incident response needs a working escalation path to AWS itself; a support role is the evidence that path exists.",
    "Create an IAM role that permits managing incidents with AWS Support."),
  cis("CIS.1.22", ["CC6"],
    "A policy granting *:* is standing admin access; auditors treat every holder as a privileged user needing justification.",
    "Replace policies that allow full administrative privileges with least-privilege policies."),
  cis("CIS.2.1", ["CC7", "CC4"],
    "CloudTrail is the audit trail auditors sample activity from; without it in all regions, the period has holes you cannot backfill.",
    "Enable CloudTrail in all regions."),
  cis("CIS.2.2", ["CC7"],
    "Log-file validation proves the audit trail wasn't altered — it turns logs into evidence.",
    "Enable CloudTrail log file validation."),
  cis("CIS.2.3", ["CC6", "C1"],
    "A publicly readable audit-log bucket leaks the account's entire activity history.",
    "Block public access on the S3 bucket that stores CloudTrail logs."),
  cis("CIS.2.4", ["CC7"],
    "Logs that reach CloudWatch can raise alarms in minutes; logs only in S3 are reviewed after the fact, if ever.",
    "Integrate CloudTrail trails with CloudWatch Logs."),
  cis("CIS.2.5", ["CC8", "CC7"],
    "AWS Config is the change record — what changed, when, from what to what. It is the backbone of change-management evidence for the infrastructure.",
    "Enable AWS Config in all regions."),
  cis("CIS.2.6", ["CC7"],
    "Access logging on the log bucket answers 'who read the audit trail' — a question auditors ask about the logs themselves.",
    "Enable S3 access logging on the CloudTrail bucket."),
  cis("CIS.2.7", ["CC6", "C1"],
    "Encrypting the audit trail with a customer-managed key limits who can read the account's activity history.",
    "Encrypt CloudTrail logs at rest with a customer-managed KMS key."),
  cis("CIS.2.8", ["CC6"],
    "Key rotation bounds the blast radius of an exposed encryption key.",
    "Enable rotation for customer-created KMS keys."),
  cis("CIS.2.9", ["CC7"],
    "VPC flow logs are the network's audit trail — without them, investigating an incident has no network record to consult.",
    "Enable VPC flow logging in all VPCs."),
  cis("CIS.3.1", ["CC7"],
    "An alarm on unauthorized API calls is detection working in practice, not just logging in principle.",
    "Create a log metric filter and alarm for unauthorized API calls."),
  cis("CIS.3.2", ["CC7", "CC6"],
    "Sign-ins without MFA should be rare and noticed; the alarm is the noticing.",
    "Create a log metric filter and alarm for console sign-in without MFA."),
  cis("CIS.3.3", ["CC7", "CC6"],
    "Root usage should be an event, not a habit — the alarm makes every use reviewable.",
    "Create a log metric filter and alarm for root account usage."),
  cis("CIS.3.4", ["CC7", "CC6"],
    "IAM policy changes alter who can do what; alerting on them is how privilege changes get a second pair of eyes.",
    "Create a log metric filter and alarm for IAM policy changes."),
  cis("CIS.3.5", ["CC7"],
    "Turning the audit trail off is the first move in covering tracks; this alarm watches the watcher.",
    "Create a log metric filter and alarm for CloudTrail configuration changes."),
  cis("CIS.3.6", ["CC7", "CC6"],
    "Repeated authentication failures are the visible edge of a credential attack.",
    "Create a log metric filter and alarm for console authentication failures."),
  cis("CIS.3.7", ["CC7"],
    "Disabling or scheduling deletion of an encryption key can silently strand or expose data; it deserves an alert.",
    "Create a log metric filter and alarm for disabling or scheduled deletion of customer-managed keys."),
  cis("CIS.3.8", ["CC7"],
    "S3 bucket policy changes can flip data from private to public in one call.",
    "Create a log metric filter and alarm for S3 bucket policy changes."),
  cis("CIS.3.9", ["CC7", "CC8"],
    "Changes to AWS Config alter the change record itself — the evidence pipeline needs its own alarm.",
    "Create a log metric filter and alarm for AWS Config configuration changes."),
  cis("CIS.3.10", ["CC7", "CC8"],
    "Security group changes are firewall changes; the alarm gives each one a review moment.",
    "Create a log metric filter and alarm for security group changes."),
  cis("CIS.3.11", ["CC7", "CC8"],
    "NACL changes alter network exposure at the subnet level.",
    "Create a log metric filter and alarm for changes to Network Access Control Lists."),
  cis("CIS.3.12", ["CC7", "CC8"],
    "New or changed gateways change how traffic can enter and leave the network.",
    "Create a log metric filter and alarm for changes to network gateways."),
  cis("CIS.3.13", ["CC7", "CC8"],
    "Route table changes redirect traffic — quietly, if nobody is alerted.",
    "Create a log metric filter and alarm for route table changes."),
  cis("CIS.3.14", ["CC7", "CC8"],
    "VPC-level changes (peering, tenancy) reshape the network boundary.",
    "Create a log metric filter and alarm for VPC changes."),
  cis("CIS.4.1", ["CC6"],
    "SSH open to the whole internet is the classic exposure finding; auditors expect management ports to be restricted.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 22."),
  cis("CIS.4.2", ["CC6"],
    "RDP open to the whole internet invites brute force against the widest audience possible.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 3389."),
  cis("CIS.4.3", ["CC6"],
    "The default security group is attached implicitly; leaving it open means new resources start exposed by default.",
    "Restrict all traffic in every VPC's default security group."),

  // ---- AWS Foundational Security Best Practices v1.0.0 (high-value subset) ----
  fsbp("IAM.1", ["CC6"],
    "A policy granting *:* is standing admin access; auditors treat every holder as a privileged user needing justification.",
    "Replace IAM policies that allow full administrative privileges with least-privilege policies."),
  fsbp("IAM.2", ["CC6"],
    "Permissions attached to individuals are invisible to group-level review and outlive role changes.",
    "Attach permissions to groups or roles and remove policies attached directly to users."),
  fsbp("IAM.3", ["CC6"],
    "Long-lived access keys accumulate exposure; rotation bounds how long a leaked key works.",
    "Rotate every IAM access key at least every 90 days."),
  fsbp("IAM.4", ["CC6"],
    "A root access key is a programmatic super-credential with no owner review path.",
    "Delete any access key on the root account."),
  fsbp("IAM.5", ["CC6"],
    "A console password without a second factor is a single stolen secret away from account access.",
    "Enable MFA for every IAM user with a console password."),
  fsbp("IAM.6", ["CC6"],
    "Hardware MFA on root removes the phishable channel for the account's most powerful identity.",
    "Register a hardware MFA device for the root account."),
  fsbp("IAM.7", ["CC6"],
    "The password policy is baseline configuration evidence auditors sample.",
    "Strengthen the IAM password policy (length, complexity, reuse, expiry)."),
  fsbp("IAM.8", ["CC6"],
    "Credentials nobody uses usually belong to people who left — offboarding reviews look here first.",
    "Remove or disable IAM user credentials unused for 90 days."),
  fsbp("S3.1", ["CC6", "C1"],
    "Account-level Block Public Access is the seatbelt that makes a single misconfigured bucket a non-event.",
    "Turn on S3 Block Public Access at the account level."),
  fsbp("S3.2", ["CC6", "C1"],
    "A publicly readable bucket is the most common cloud data leak there is.",
    "Block public read access on every bucket."),
  fsbp("S3.3", ["CC6", "C1"],
    "Publicly writable storage lets anyone plant or replace your data.",
    "Block public write access on every bucket."),
  fsbp("S3.4", ["CC6", "C1"],
    "Encryption at rest is table-stakes evidence for data protection questions.",
    "Enable default server-side encryption on every bucket."),
  fsbp("S3.5", ["CC6", "C1"],
    "Allowing plain-HTTP requests lets data cross the network unencrypted.",
    "Add a bucket policy denying requests that don't use TLS (aws:SecureTransport)."),
  fsbp("S3.8", ["CC6", "C1"],
    "Bucket-level Block Public Access protects buckets even when the account-level guard is loosened.",
    "Turn on Block Public Access on each bucket."),
  fsbp("CloudTrail.1", ["CC7", "CC4"],
    "CloudTrail is the audit trail auditors sample activity from; a multi-region trail leaves no regional blind spots.",
    "Create a multi-region CloudTrail trail capturing management events."),
  fsbp("CloudTrail.2", ["CC6", "C1"],
    "Encrypting the audit trail limits who can read the account's activity history.",
    "Enable KMS encryption on CloudTrail logs."),
  fsbp("CloudTrail.4", ["CC7"],
    "Log-file validation proves the audit trail wasn't altered — it turns logs into evidence.",
    "Enable CloudTrail log file validation."),
  fsbp("CloudTrail.5", ["CC7"],
    "Logs that reach CloudWatch can raise alarms in minutes instead of being reviewed after the fact.",
    "Send CloudTrail logs to CloudWatch Logs."),
  fsbp("Config.1", ["CC8", "CC7"],
    "AWS Config is the change record — the backbone of change-management evidence for the infrastructure.",
    "Enable AWS Config with resource recording in this region."),
  fsbp("EC2.2", ["CC6"],
    "The default security group is attached implicitly; leaving it open means new resources start exposed by default.",
    "Restrict all traffic in every VPC's default security group."),
  fsbp("EC2.3", ["CC6", "C1"],
    "A public EBS snapshot hands a full disk image to anyone who asks.",
    "Make EBS snapshots private."),
  fsbp("EC2.6", ["CC7"],
    "VPC flow logs are the network's audit trail for incident investigation.",
    "Enable VPC flow logging in all VPCs."),
  fsbp("EC2.7", ["CC6", "C1"],
    "Default EBS encryption makes every new volume encrypted without anyone remembering to ask.",
    "Enable EBS encryption by default in this region."),
  fsbp("EC2.8", ["CC6"],
    "IMDSv2 stops the credential-stealing trick (SSRF against the metadata endpoint) that turned many web bugs into cloud breaches.",
    "Require IMDSv2 on EC2 instances."),
  fsbp("EC2.13", ["CC6"],
    "SSH open to the whole internet is the classic exposure finding.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 22."),
  fsbp("EC2.14", ["CC6"],
    "RDP open to the whole internet invites brute force against the widest audience possible.",
    "Remove security group rules allowing ingress from 0.0.0.0/0 to port 3389."),
  fsbp("RDS.1", ["CC6", "C1"],
    "A public RDS snapshot hands your database to anyone who asks.",
    "Make RDS snapshots private."),
  fsbp("RDS.2", ["CC6"],
    "A database reachable from the internet exposes your data store to the whole world's password guesses.",
    "Disable public accessibility on RDS instances."),
  fsbp("RDS.3", ["CC6", "C1"],
    "Encryption at rest for databases is one of the first data-protection answers auditors verify.",
    "Enable storage encryption on RDS instances."),
  fsbp("RDS.11", ["A1"],
    "Automatic backups are the recovery story for the availability criteria — no backups, no story.",
    "Enable automatic backups with a sensible retention period on RDS instances."),
  fsbp("DynamoDB.2", ["A1"],
    "Point-in-time recovery is what lets you answer 'and if the table is corrupted or deleted?'",
    "Enable point-in-time recovery on DynamoDB tables."),
  fsbp("Lambda.1", ["CC6"],
    "A function policy that allows public invocation makes your code an open endpoint.",
    "Remove public access from Lambda function resource policies."),
  fsbp("Lambda.2", ["CC7", "CC8"],
    "Runtimes past end-of-life stop receiving security patches — running one is unmanaged risk.",
    "Migrate Lambda functions to supported runtimes."),
  fsbp("KMS.4", ["CC6"],
    "Key rotation bounds the blast radius of an exposed encryption key.",
    "Enable rotation on customer-managed KMS keys."),
  fsbp("GuardDuty.1", ["CC7"],
    "GuardDuty is managed threat detection; auditors read it as the intrusion-detection control for the account.",
    "Enable GuardDuty in this region."),
  fsbp("ACM.1", ["CC6"],
    "An expired certificate breaks TLS — availability and trust fail at the same moment.",
    "Renew or remove expiring/expired ACM certificates (enable managed renewal)."),
  // ---- Mapping expansion, 2026.09.1 -------------------------------------------------
  // A live account (2026-09-07) put 40 FAILING controls outside the criteria entirely — more
  // failures unmapped than mapped, including a CRITICAL. Everything below was failing or
  // sits in the same family, so the report files what an auditor would actually raise.

  // Account & identity
  fsbp("Account.1", ["CC2", "CC7"],
    "An account with no security contact is one AWS cannot reach when it spots abuse — auditors read it as a gap in the incident-notification path.",
    "Set the alternate security contact on the account."),
  fsbp("IAM.21", ["CC6"],
    "A customer-managed policy with wildcard actions grants more than anyone reviewed; auditors sample policies for exactly this.",
    "Replace wildcard actions in customer-managed policies with the specific actions needed."),
  fsbp("IAM.9", ["CC6"],
    "Root without MFA means one password protects the entire account — the highest-impact single control there is.",
    "Enable MFA on the root account."),
  fsbp("IAM.18", ["CC7", "CC9"],
    "Incident response needs a working escalation path to AWS itself; a support role is the evidence that path exists.",
    "Create an IAM role granting access to AWS Support."),

  // Encryption key access
  fsbp("KMS.1", ["CC6", "C1"],
    "A policy allowing decryption against every key defeats the point of separating keys — one compromised principal reads everything.",
    "Scope decryption permissions to the specific keys a principal needs."),
  fsbp("KMS.2", ["CC6", "C1"],
    "An inline policy allowing decryption on all keys is the same exposure as a managed one, and harder to review.",
    "Remove blanket decryption permissions from inline policies and scope them per key."),

  // Threat detection & vulnerability management
  fsbp("Inspector.1", ["CC7"],
    "Auditors ask how you learn a running instance has a known vulnerability; Inspector scanning is the usual answer.",
    "Enable Amazon Inspector EC2 scanning."),
  fsbp("Inspector.2", ["CC7"],
    "Container images inherit vulnerabilities from their base layers, and nothing surfaces them unless the registry is scanned.",
    "Enable Amazon Inspector ECR scanning."),
  fsbp("Inspector.3", ["CC7"],
    "Function code carries dependency vulnerabilities like anything else, and is easy to leave unscanned.",
    "Enable Amazon Inspector Lambda code scanning."),
  fsbp("Inspector.4", ["CC7"],
    "Standard Lambda scanning covers the runtime and packages behind your functions.",
    "Enable Amazon Inspector Lambda standard scanning."),
  fsbp("ECR.1", ["CC7", "CC8"],
    "An unscanned registry ships known-vulnerable images straight to production, and change management cannot show they were checked.",
    "Turn on image scanning for every private ECR repository."),
  fsbp("Macie.1", ["C1"],
    "Confidentiality answers start with knowing where sensitive data actually sits; Macie is the discovery control.",
    "Enable Amazon Macie."),

  // Public exposure
  fsbp("SSM.7", ["CC6", "C1"],
    "A publicly shared Systems Manager document can leak the commands and parameters you run across the estate.",
    "Enable the block-public-sharing setting for SSM documents."),
  fsbp("EC2.182", ["CC6", "C1"],
    "A publicly restorable snapshot hands a full disk image to anyone who asks — the same exposure as a public bucket.",
    "Enable block public access for EBS snapshots."),
  fsbp("EC2.15", ["CC6"],
    "A subnet that auto-assigns public IPs puts new workloads on the internet by default, before anyone decides they should be.",
    "Turn off auto-assign public IPv4 on subnets that should stay private."),
  fsbp("EC2.172", ["CC6"],
    "VPC block public access is the account-level guard that survives a single bad route or gateway.",
    "Enable VPC Block Public Access to block internet gateway traffic."),

  // Application front doors
  fsbp("AppSync.5", ["CC6"],
    "An API key is a shared static secret with no user identity behind it — auditors treat it as unauthenticated access.",
    "Authenticate AppSync APIs with IAM, Cognito or OIDC instead of API keys."),
  fsbp("AppSync.2", ["CC7"],
    "Without field-level logging there is no record of what a caller actually asked for.",
    "Enable field-level logging on AppSync APIs."),
  fsbp("APIGateway.1", ["CC7"],
    "Execution logging is the request-level record auditors sample when asking what an API did.",
    "Enable execution logging on REST and WebSocket API stages."),
  fsbp("APIGateway.9", ["CC7"],
    "Access logs answer who called the API and when — the question that follows every incident.",
    "Configure access logging on API Gateway V2 stages."),
  fsbp("APIGateway.4", ["CC6", "CC7"],
    "A public API with no WAF in front has no layer between the internet and your handlers.",
    "Associate a WAF Web ACL with the API."),
  fsbp("APIGateway.11", ["CC6", "C1"],
    "An out-of-date TLS policy on a custom domain keeps weak ciphers alive for every client.",
    "Move API Gateway domain names onto a current security policy."),
  fsbp("APIGateway.3", ["CC7"],
    "Tracing is how an operations team reconstructs a failing request; auditors read it as monitoring maturity.",
    "Enable X-Ray tracing on REST API stages."),

  // Customer identity
  fsbp("Cognito.2", ["CC6"],
    "An identity pool that allows unauthenticated identities hands AWS credentials to anyone who asks.",
    "Disable unauthenticated identities on the identity pool."),
  fsbp("Cognito.5", ["CC6"],
    "MFA for your end users is the same control auditors check for your staff, applied to the people whose data it is.",
    "Enable MFA on the Cognito user pool."),
  fsbp("Cognito.3", ["CC6"],
    "A weak user-pool password policy is the password-policy finding, moved to your customers.",
    "Strengthen the user pool's password policy (length, complexity, reuse)."),
  fsbp("Cognito.1", ["CC6", "CC7"],
    "Threat protection is what notices credential stuffing against your sign-in, rather than discovering it afterwards.",
    "Activate threat protection in full-function mode for standard authentication."),
  fsbp("Cognito.4", ["CC6", "CC7"],
    "Custom authentication flows need the same protection as the standard one, or they become the way in.",
    "Activate threat protection in full-function mode for custom authentication."),
  fsbp("Cognito.6", ["A1"],
    "Deleting a user pool destroys every account in it, irreversibly.",
    "Enable deletion protection on the user pool."),

  // Durability & change control
  fsbp("DynamoDB.6", ["A1"],
    "Deletion protection is what stops one mistaken call removing a table and everything in it.",
    "Enable deletion protection on production tables."),
  fsbp("CloudFormation.3", ["CC8", "A1"],
    "Termination protection is the change-management guard on the stacks your infrastructure is defined by.",
    "Enable termination protection on production stacks."),
  fsbp("CloudFormation.4", ["CC8"],
    "A stack with no service role deploys with whoever ran it, so the blast radius is a person rather than a defined permission set.",
    "Attach a service role to each stack so deployments run with scoped permissions."),

  // Logging & retention
  fsbp("S3.9", ["CC7"],
    "Server access logging answers who read an object — the question that matters after a suspected leak.",
    "Enable server access logging on buckets holding meaningful data."),
  fsbp("S3.13", ["A1", "C1"],
    "A lifecycle configuration is how a retention policy becomes something you can show rather than assert.",
    "Add lifecycle rules that match your stated retention period."),
  fsbp("SSM.6", ["CC7", "CC8"],
    "Automation that runs unlogged changes the estate with no record of what it did.",
    "Send SSM Automation output to CloudWatch Logs."),
  fsbp("StepFunctions.1", ["CC7"],
    "A workflow with logging off leaves no trace of what ran, in what order, or where it stopped.",
    "Turn on logging for state machines."),

  // Private connectivity
  fsbp("EC2.10", ["CC6"],
    "Interface endpoints keep control-plane traffic off the public internet, which is the network boundary auditors ask you to describe.",
    "Create the EC2 interface endpoint in VPCs that call the EC2 API."),
  fsbp("EC2.55", ["CC6"],
    "Without a private endpoint, image pulls cross the internet to reach the registry.",
    "Create an interface endpoint for the ECR API."),
  fsbp("EC2.56", ["CC6"],
    "The Docker Registry endpoint keeps the image layers themselves on private paths.",
    "Create an interface endpoint for Docker Registry (ecr.dkr)."),
  fsbp("EC2.57", ["CC6"],
    "Systems Manager reaches instances without opening inbound access — only if the private endpoint exists.",
    "Create an interface endpoint for Systems Manager."),
  fsbp("EC2.58", ["CC7"],
    "Incident Manager contacts must be reachable during an incident, including one that affects internet egress.",
    "Create an interface endpoint for Incident Manager Contacts."),
  fsbp("EC2.60", ["CC7"],
    "Incident Manager is the paging path; routing it privately keeps it working when the network is the problem.",
    "Create an interface endpoint for Incident Manager."),

];

const byId = new Map<string, MappedCheck>(MAPPING.map((m) => [`${m.standard}:${m.checkId}`, m]));

/** Look up the mapping for a control, by standard + Security Hub control id. */
export function findMapping(standard: StandardId, checkId: string): MappedCheck | undefined {
  return byId.get(`${standard}:${checkId}`);
}
